name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Add any necessary build steps here, such as installing dependencies, compiling code, etc.
       
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 3.109.143.238
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/ubuntu/githubCICD
            cd /home/ubuntu/githubCICD
            sudo apt update
            'rm -rf .git .github .gitignore * && git clone -b main https://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@github.com/CaptainTron/IG_Automation_Bot.git .' 
            pip install -r requirement.txt
            chmod +x automate.sh
            date
            if ! command -v ngrok &> /dev/null; then
            echo "ngrok is not installed. Installing..."
            # Download and install ngrok
            curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc \
            | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && echo "deb https://ngrok-agent.s3.amazonaws.com buster main" \
            | sudo tee /etc/apt/sources.list.d/ngrok.list && sudo apt update && sudo apt install ngrok
            
            echo "Adding your authtoken to the default ngrok.yml"
            ngrok config add-authtoken 2dNF1VLg5bFPHtESIyKtSO2xqAI_4e4mjYsxDjoXtxo1Qskzf
            else
              echo "ngrok is already installed."
            fi
