name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Add any necessary build steps here, such as installing dependencies, compiling code, etc.
      
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: 3.109.143.238
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir /home/ubuntu/vaibhav
            # Add any additional deployment steps here
